spring:
  application:
    name: IVR-api
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: ./src/main/resources/sql/schema.sql    UTILISER UNIQUEMENT POUR GENERER LE SCRIPT SQL DES TABLES



      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: update


server:
  port: ${SERVER_PORT:8080}