spring:
  application:
    name: IVR-api
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:default}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: ./src/main/resources/sql/schema.sql
      hibernate:

        show_sql: true
        hbm2ddl:
          auto: none
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}